sudo: required
language: python
python:
  - '3.4'
  - '3.5'
cache: pip

services:
  - docker

before_install:
  - docker pull noazark/ledger

install:
  - pip install tox-travis codecov

script:
  - tox


after_success:
  - codecov
